### ISSUE TITLE
Can not generate static callgraph

### ISSUE THREAD

**Issue by SandZn** [emarteca/stubbifier#1]
Hi authors,

According to the existing file "genStaticCG.sh", I cannot run the script successfully and generate a static call graph for the program (e.g. serve-favicon), which means the file static_callgraph.csv was empty.

I found there are two issues that prevent the shell from generating a static call graph:
1. The variable "$ANALYSIS_HOME" is undefined, and can not be echoed out. 
2. An error occured: "A fatal error occurred: Error reading /home/stubbifier/qlpack.yml: Invalid pack name 'stubbifier-staticCG'. A pack name must contain only lowercase ASCII letters, ASCII digits, and hyphens. (through reference chain: com.semmle.frontend.packs.QlPack["name"])"

regarding the 1st issue, I removed the option "--search-path=$ANALYSIS_HOME".
regarding the 2nd issue, I modified the name "stubbifier-staticCG" to "stubbifierstaticcg" (in the file qlpack.yml)

Then I can get a call graph showed in the file static_callgraph.csv.

However, I've no idea whether the result is wrong or not due to the modification I've made.

**Comment by emarteca** [comment]
Hey @SandZn , thanks for catching this! The problem was due to an update in CodeQL. I just pushed an edit to the docker build script that hardcodes the version of CodeQL to ensure that 1) it works and 2) this doesn't happen again.
Can you try building the static callgraph with these updates and see if your issue is fixed?

**Comment by emarteca** [comment]
I'm closing this issue due to the fix above

**Comment by SandZn** [comment]
@emarteca Hi Ellen, sorry for my late reply and thank you for fixing this. I confirm that this issue is fixed, and I can successfully build the static callgraph. It's so great that I don't need to download CodeQL zip file. Thanks again!

**Comment by emarteca** [comment]
Great, I'm glad it works for you now! Thanks for confirming :)
